import { ProductDetail } from './product.interface';

export const products: ProductDetail[] = [
  {
    id: '1',
    img: 'https://i.pinimg.com/736x/bd/9c/be/bd9cbeea5a121427235d5f85e85c8318.jpg',
    title: 'Cappuccino',
    description: 'Strong coffee with frothed milk',
    size: ['small', 'medium', 'large'],
    customize: {
      milk: [
        'oat milk',
        'whole milk',
        'almond milk',
        'skim milk',
        'coconut milk',
        'soy milk',
      ],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['coconut', 'almond', 'vanilla', 'chocolate'],
    },
    amount: 5.49,
    category: { id: 1, imgCoffee: 'link-to-category-img', title: 'Hot Coffee' },
    location: {
      id: 1,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 1',
      address: 'Tashkent, Street 1',
      workingTime: '8 AM - 8 PM',
    },
  },
  {
    id: '2',
    img: 'https://example.com/image2.jpg',
    title: 'Latte',
    description: 'Smooth espresso with steamed milk',
    size: ['small', 'medium', 'large'],
    customize: {
      milk: [
        'oat milk',
        'whole milk',
        'almond milk',
        'skim milk',
        'coconut milk',
        'soy milk',
      ],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['coconut', 'almond', 'vanilla', 'chocolate'],
    },
    amount: 4.99,
    category: {
      id: 2,
      imgCoffee: 'link-to-category-img',
      title: 'Cold Coffee',
    },
    location: {
      id: 2,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 2',
      address: 'Tashkent, Street 2',
      workingTime: '9 AM - 9 PM',
    },
  },
  {
    id: '3',
    img: 'https://example.com/image3.jpg',
    title: 'Mocha',
    description: 'Espresso with chocolate syrup and steamed milk',
    size: ['small', 'medium', 'large'],
    customize: {
      milk: ['whole milk', 'soy milk', 'almond milk'],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['chocolate', 'hazelnut', 'vanilla'],
    },
    amount: 6.99,
    category: {
      id: 3,
      imgCoffee: 'link-to-category-img',
      title: 'Health Coffee',
    },
    location: {
      id: 3,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 3',
      address: 'Tashkent, Street 3',
      workingTime: '7 AM - 7 PM',
    },
  },
  {
    id: '4',
    img: 'https://example.com/image4.jpg',
    title: 'Americano',
    description: 'Espresso with hot water for a strong, black coffee',
    size: ['small', 'medium', 'large'],
    customize: {
      milk: ['whole milk', 'almond milk', 'oat milk'],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['vanilla', 'hazelnut'],
    },
    amount: 4.49,
    category: { id: 4, imgCoffee: 'link-to-category-img', title: 'Hot Coffee' },
    location: {
      id: 4,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 4',
      address: 'Tashkent, Street 4',
      workingTime: '10 AM - 10 PM',
    },
  },
  {
    id: '5',
    img: 'https://example.com/image5.jpg',
    title: 'Flat White',
    description: 'Espresso with steamed milk and a velvety texture',
    size: ['small', 'medium', 'large'],
    customize: {
      milk: ['whole milk', 'oat milk', 'almond milk'],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['caramel', 'chocolate'],
    },
    amount: 5.49,
    category: {
      id: 5,
      imgCoffee: 'link-to-category-img',
      title: 'Health Coffee',
    },
    location: {
      id: 5,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 5',
      address: 'Tashkent, Street 5',
      workingTime: '8 AM - 8 PM',
    },
  },
  {
    id: '6',
    img: 'https://example.com/image6.jpg',
    title: 'Iced Coffee',
    description: 'Cold coffee with ice and a refreshing flavor',
    size: ['small', 'medium', 'large'],
    customize: {
      milk: ['whole milk', 'oat milk', 'almond milk'],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['vanilla', 'chocolate', 'caramel'],
    },
    amount: 4.99,
    category: {
      id: 2,
      imgCoffee: 'link-to-category-img',
      title: 'Cold Coffee',
    },
    location: {
      id: 6,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 6',
      address: 'Tashkent, Street 6',
      workingTime: '9 AM - 6 PM',
    },
  },
  {
    id: '7',
    img: 'https://example.com/image7.jpg',
    title: 'Nitro Coffee',
    description:
      'Cold-brewed coffee infused with nitrogen for a creamy texture',
    size: ['small', 'medium'],
    customize: {
      milk: ['whole milk', 'almond milk', 'oat milk'],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['chocolate', 'vanilla'],
    },
    amount: 6.49,
    category: {
      id: 2,
      imgCoffee: 'link-to-category-img',
      title: 'Cold Coffee',
    },
    location: {
      id: 7,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 7',
      address: 'Tashkent, Street 7',
      workingTime: '6 AM - 6 PM',
    },
  },
  {
    id: '8',
    img: 'https://example.com/image8.jpg',
    title: 'Espresso Martini',
    description: 'A cocktail made with espresso, vodka, and coffee liqueur',
    size: ['small'],
    customize: {
      milk: ['whole milk', 'almond milk'],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['vanilla', 'hazelnut'],
    },
    amount: 7.49,
    category: {
      id: 3,
      imgCoffee: 'link-to-category-img',
      title: 'Health Coffee',
    },
    location: {
      id: 8,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 8',
      address: 'Tashkent, Street 8',
      workingTime: '9 AM - 11 PM',
    },
  },
  {
    id: '9',
    img: 'https://example.com/image9.jpg',
    title: 'Caramel Macchiato',
    description: 'Espresso with caramel syrup and steamed milk',
    size: ['small', 'medium', 'large'],
    customize: {
      milk: ['oat milk', 'soy milk', 'whole milk'],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['caramel', 'hazelnut'],
    },
    amount: 5.99,
    category: { id: 1, imgCoffee: 'link-to-category-img', title: 'Hot Coffee' },
    location: {
      id: 9,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 9',
      address: 'Tashkent, Street 9',
      workingTime: '8 AM - 6 PM',
    },
  },
  {
    id: '10',
    img: 'https://example.com/image10.jpg',
    title: 'Iced Latte',
    description: 'Iced espresso with chilled milk',
    size: ['small', 'medium', 'large'],
    customize: {
      milk: ['whole milk', 'almond milk', 'oat milk'],
      cream: ['with whipped cream', 'without whipped cream'],
      syrup: ['chocolate', 'vanilla'],
    },
    amount: 5.49,
    category: {
      id: 2,
      imgCoffee: 'link-to-category-img',
      title: 'Cold Coffee',
    },
    location: {
      id: 10,
      imgCafe: 'link-to-cafe-img',
      title: 'Cafe 10',
      address: 'Tashkent, Street 10',
      workingTime: '10 AM - 8 PM',
    },
  },
];
